version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - loggercheck
    - makezero
    - nilerr
    - noctx
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: false
    exhaustive:
      check:
        - map
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
    funlen:
      lines: 2000
      statements: 200
    gocognit:
      min-complexity: 50
    gocritic:
      disabled-checks:
        - commentFormatting
        - ifElseChain
        - elseif
        - singleCaseSwitch
        - appendAssign
      settings:
        captLocal:
          paramsOnly: true
        underef:
          skipRecvDeref: false
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: gofrs' package is not go module
    gosec:
      excludes:
        - G601
        - G404
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: false
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA1029
        - -SA9003
        - -ST1000
        - -ST1020
        - -ST1021
        - -ST1022
        - -QF1008
        - -QF1003
        - -QF1001

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
