services:
  db:
    image: postgres:16.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cisab
      - POSTGRES_PORT=5433
      - PGUSER=postgres
    ports:
      - '5433:5432' # using 5433 to avoid conflict with local postgres
    volumes:
      - cisabdb:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 120s
      retries: 12

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=cisab
      - PORT=8080
    ports:
      - '8080:8080'

volumes:
  cisabdb:
    driver: local
