# Local environment configuration
environment: local

# Server configuration
server:
  port: 8080

jwt:
  secret: 'default-development-secret-key'
  ttl: 86400 # in seconds (1 day)

# Database configuration
database:
  host: localhost
  port: 5433
  user: postgres
  password: password
  name: knovel
